//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "TrackPage.xaml.h"

void ::GUI::TrackPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///TrackPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::GUI::TrackPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Button^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&TrackPage::Button_Click);
            }
            break;
        case 2:
            {
                this->Tom19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom19_Tapped);
            }
            break;
        case 3:
            {
                this->Tom18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom18_Tapped);
            }
            break;
        case 4:
            {
                this->Tom17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom17_Tapped);
            }
            break;
        case 5:
            {
                this->Tom16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom16_Tapped);
            }
            break;
        case 6:
            {
                this->Tom14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom14_Tapped);
            }
            break;
        case 7:
            {
                this->Tom13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom13_Tapped);
            }
            break;
        case 8:
            {
                this->Tom12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom12_Tapped);
            }
            break;
        case 9:
            {
                this->Tom11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom11_Tapped);
            }
            break;
        case 10:
            {
                this->Tom9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom9_Tapped);
            }
            break;
        case 11:
            {
                this->Tom8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom8_Tapped);
            }
            break;
        case 12:
            {
                this->Tom7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom7_Tapped);
            }
            break;
        case 13:
            {
                this->Tom6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom6_Tapped);
            }
            break;
        case 14:
            {
                this->Tom4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom4_Tapped);
            }
            break;
        case 15:
            {
                this->Tom3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom3_Tapped);
            }
            break;
        case 16:
            {
                this->Tom2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom2_Tapped);
            }
            break;
        case 17:
            {
                this->Tom1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Tom1_Tapped);
            }
            break;
        case 18:
            {
                this->CHat19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat19_Tapped);
            }
            break;
        case 19:
            {
                this->CHat18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat18_Tapped);
            }
            break;
        case 20:
            {
                this->CHat17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat17_Tapped);
            }
            break;
        case 21:
            {
                this->CHat16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat16_Tapped);
            }
            break;
        case 22:
            {
                this->CHat14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat14_Tapped);
            }
            break;
        case 23:
            {
                this->CHat13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat13_Tapped);
            }
            break;
        case 24:
            {
                this->CHat12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat12_Tapped);
            }
            break;
        case 25:
            {
                this->CHat11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat11_Tapped);
            }
            break;
        case 26:
            {
                this->CHat9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat9_Tapped);
            }
            break;
        case 27:
            {
                this->CHat8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat8_Tapped);
            }
            break;
        case 28:
            {
                this->CHat7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat7_Tapped);
            }
            break;
        case 29:
            {
                this->CHat6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat6_Tapped);
            }
            break;
        case 30:
            {
                this->CHat4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat4_Tapped);
            }
            break;
        case 31:
            {
                this->CHat3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat3_Tapped);
            }
            break;
        case 32:
            {
                this->CHat2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat2_Tapped);
            }
            break;
        case 33:
            {
                this->CHat1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::CHat1_Tapped);
            }
            break;
        case 34:
            {
                this->OHat19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat19_Tapped);
            }
            break;
        case 35:
            {
                this->OHat18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat18_Tapped);
            }
            break;
        case 36:
            {
                this->OHat17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat17_Tapped);
            }
            break;
        case 37:
            {
                this->OHat16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat16_Tapped);
            }
            break;
        case 38:
            {
                this->OHat14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat14_Tapped);
            }
            break;
        case 39:
            {
                this->OHat13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat13_Tapped);
            }
            break;
        case 40:
            {
                this->OHat12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat12_Tapped);
            }
            break;
        case 41:
            {
                this->OHat11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat11_Tapped);
            }
            break;
        case 42:
            {
                this->OHat9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat9_Tapped);
            }
            break;
        case 43:
            {
                this->OHat8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat8_Tapped);
            }
            break;
        case 44:
            {
                this->OHat7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat7_Tapped);
            }
            break;
        case 45:
            {
                this->OHat6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat6_Tapped);
            }
            break;
        case 46:
            {
                this->OHat4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat4_Tapped);
            }
            break;
        case 47:
            {
                this->OHat3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat3_Tapped);
            }
            break;
        case 48:
            {
                this->OHat2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat2_Tapped);
            }
            break;
        case 49:
            {
                this->OHat1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::OHat1_Tapped);
            }
            break;
        case 50:
            {
                this->Clap19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap19_Tapped);
            }
            break;
        case 51:
            {
                this->Clap18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap18_Tapped);
            }
            break;
        case 52:
            {
                this->Clap17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap17_Tapped);
            }
            break;
        case 53:
            {
                this->Clap16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap16_Tapped);
            }
            break;
        case 54:
            {
                this->Clap14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap14_Tapped);
            }
            break;
        case 55:
            {
                this->Clap13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap13_Tapped);
            }
            break;
        case 56:
            {
                this->Clap12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap12_Tapped);
            }
            break;
        case 57:
            {
                this->Clap11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap11_Tapped);
            }
            break;
        case 58:
            {
                this->Clap9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap9_Tapped);
            }
            break;
        case 59:
            {
                this->Clap8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap8_Tapped);
            }
            break;
        case 60:
            {
                this->Clap7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap7_Tapped);
            }
            break;
        case 61:
            {
                this->Clap6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap6_Tapped);
            }
            break;
        case 62:
            {
                this->Clap4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap4_Tapped);
            }
            break;
        case 63:
            {
                this->Clap3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap3_Tapped);
            }
            break;
        case 64:
            {
                this->Clap2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap2_Tapped);
            }
            break;
        case 65:
            {
                this->Clap1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Clap1_Tapped);
            }
            break;
        case 66:
            {
                this->Snare19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare19_Tapped);
            }
            break;
        case 67:
            {
                this->Snare18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare18_Tapped);
            }
            break;
        case 68:
            {
                this->Snare17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare17_Tapped);
            }
            break;
        case 69:
            {
                this->Snare16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare16_Tapped);
            }
            break;
        case 70:
            {
                this->Snare14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare14_Tapped);
            }
            break;
        case 71:
            {
                this->Snare13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare13_Tapped);
            }
            break;
        case 72:
            {
                this->Snare12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare12_Tapped);
            }
            break;
        case 73:
            {
                this->Snare11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare11_Tapped);
            }
            break;
        case 74:
            {
                this->Snare9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare9_Tapped);
            }
            break;
        case 75:
            {
                this->Snare8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare8_Tapped);
            }
            break;
        case 76:
            {
                this->Snare7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare7_Tapped);
            }
            break;
        case 77:
            {
                this->Snare6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare6_Tapped);
            }
            break;
        case 78:
            {
                this->Snare4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare4_Tapped);
            }
            break;
        case 79:
            {
                this->Snare3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare3_Tapped);
            }
            break;
        case 80:
            {
                this->Snare2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare2_Tapped);
            }
            break;
        case 81:
            {
                this->Snare1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Snare1_Tapped);
            }
            break;
        case 82:
            {
                this->Kick19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick19_Tapped);
            }
            break;
        case 83:
            {
                this->Kick18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick18_Tapped);
            }
            break;
        case 84:
            {
                this->Kick17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick17_Tapped);
            }
            break;
        case 85:
            {
                this->Kick16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick16_Tapped);
            }
            break;
        case 86:
            {
                this->Kick14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick14_Tapped);
            }
            break;
        case 87:
            {
                this->Kick13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick13_Tapped);
            }
            break;
        case 88:
            {
                this->Kick12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick12_Tapped);
            }
            break;
        case 89:
            {
                this->Kick11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick11_Tapped);
            }
            break;
        case 90:
            {
                this->Kick9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick9_Tapped);
            }
            break;
        case 91:
            {
                this->Kick8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick8_Tapped);
            }
            break;
        case 92:
            {
                this->Kick7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick7_Tapped);
            }
            break;
        case 93:
            {
                this->Kick6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick6_Tapped);
            }
            break;
        case 94:
            {
                this->Kick4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick4_Tapped);
            }
            break;
        case 95:
            {
                this->Kick3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick3_Tapped);
            }
            break;
        case 96:
            {
                this->Kick2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick2_Tapped);
            }
            break;
        case 97:
            {
                this->Kick1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::GUI::TrackPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage::Kick1_Tapped);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::GUI::TrackPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


