#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace GUI
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class TrackPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick19;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick18;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick17;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick1;
    };
}

