//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "TrackPage44.xaml.h"

void ::SimpG::TrackPage44::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///TrackPage44.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SimpG::TrackPage44::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->trackGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 2:
            {
                this->KG1 = safe_cast<::Windows::UI::Xaml::Controls::Border^>(__target);
            }
            break;
        case 3:
            {
                this->playpause = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->playpause))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&TrackPage44::Button_Click_1);
            }
            break;
        case 4:
            {
                this->clear = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->clear))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&TrackPage44::clear_Click);
            }
            break;
        case 5:
            {
                this->New = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->New))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&TrackPage44::Button_Click);
            }
            break;
        case 6:
            {
                this->playhead = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
            }
            break;
        case 7:
            {
                this->Pause = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Pause))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&TrackPage44::Pause_Click);
            }
            break;
        case 8:
            {
                this->playheadBar = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
            }
            break;
        case 9:
            {
                this->loc1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc1tap);
            }
            break;
        case 10:
            {
                this->loc2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc2tap);
            }
            break;
        case 11:
            {
                this->loc3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc3tap);
            }
            break;
        case 12:
            {
                this->loc4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc4tap);
            }
            break;
        case 13:
            {
                this->loc6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc6tap);
            }
            break;
        case 14:
            {
                this->loc7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc7tap);
            }
            break;
        case 15:
            {
                this->loc8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc8tap);
            }
            break;
        case 16:
            {
                this->loc9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc9tap);
            }
            break;
        case 17:
            {
                this->loc11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc11tap);
            }
            break;
        case 18:
            {
                this->loc12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc12tap);
            }
            break;
        case 19:
            {
                this->loc13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc13tap);
            }
            break;
        case 20:
            {
                this->loc14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc14tap);
            }
            break;
        case 21:
            {
                this->loc16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc16tap);
            }
            break;
        case 22:
            {
                this->loc17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc17tap);
            }
            break;
        case 23:
            {
                this->loc18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc18tap);
            }
            break;
        case 24:
            {
                this->loc19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->loc19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::loc19tap);
            }
            break;
        case 25:
            {
                this->_1000000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 26:
            {
                this->_1000001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 27:
            {
                this->_1000010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 28:
            {
                this->_1000011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 29:
            {
                this->_1000100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 30:
            {
                this->_1000101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 31:
            {
                this->_1000110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 32:
            {
                this->_1000111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 33:
            {
                this->_1001000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 34:
            {
                this->_1001001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 35:
            {
                this->_1001010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 36:
            {
                this->_1001011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 37:
            {
                this->_1001100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 38:
            {
                this->_1001101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 39:
            {
                this->_1001110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 40:
            {
                this->_1001111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 41:
            {
                this->_1010000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 42:
            {
                this->_1010001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 43:
            {
                this->_1010010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 44:
            {
                this->_1010011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 45:
            {
                this->_1010100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 46:
            {
                this->_1010101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 47:
            {
                this->_1010110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 48:
            {
                this->_1010111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 49:
            {
                this->_1011000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 50:
            {
                this->_1011001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 51:
            {
                this->_1011010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 52:
            {
                this->_1011011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 53:
            {
                this->_1011100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 54:
            {
                this->_1011101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 55:
            {
                this->_1011110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 56:
            {
                this->_1011111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 57:
            {
                this->_1100000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 58:
            {
                this->_1100001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 59:
            {
                this->_1100010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 60:
            {
                this->_1100011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 61:
            {
                this->_1100100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 62:
            {
                this->_1100101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 63:
            {
                this->_1100110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 64:
            {
                this->_1100111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 65:
            {
                this->_1101000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 66:
            {
                this->_1101001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 67:
            {
                this->_1101010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 68:
            {
                this->_1101011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 69:
            {
                this->_1101100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 70:
            {
                this->_1101101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 71:
            {
                this->_1101110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 72:
            {
                this->_1101111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 73:
            {
                this->_1110000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 74:
            {
                this->_1110001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 75:
            {
                this->_1110010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 76:
            {
                this->_1110011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 77:
            {
                this->_1110100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 78:
            {
                this->_1110101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 79:
            {
                this->_1110110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 80:
            {
                this->_1110111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 81:
            {
                this->_1111000 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 82:
            {
                this->_1111001 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 83:
            {
                this->_1111010 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 84:
            {
                this->_1111011 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 85:
            {
                this->_1111100 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 86:
            {
                this->_1111101 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 87:
            {
                this->_1111110 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 88:
            {
                this->_1111111 = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(__target);
            }
            break;
        case 89:
            {
                this->kickicon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->kickicon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleKick);
            }
            break;
        case 90:
            {
                this->snareicon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->snareicon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleSnare);
            }
            break;
        case 91:
            {
                this->ohaticon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->ohaticon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleOhat);
            }
            break;
        case 92:
            {
                this->clapicon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->clapicon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleClap);
            }
            break;
        case 93:
            {
                this->chaticon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->chaticon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleChat);
            }
            break;
        case 94:
            {
                this->tomicon = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->tomicon))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::sampleTom);
            }
            break;
        case 95:
            {
                this->Tom19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom19_Tapped);
            }
            break;
        case 96:
            {
                this->Tom18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom18_Tapped);
            }
            break;
        case 97:
            {
                this->Tom17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom17_Tapped);
            }
            break;
        case 98:
            {
                this->Tom16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom16_Tapped);
            }
            break;
        case 99:
            {
                this->Tom14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom14_Tapped);
            }
            break;
        case 100:
            {
                this->Tom13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom13_Tapped);
            }
            break;
        case 101:
            {
                this->Tom12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom12_Tapped);
            }
            break;
        case 102:
            {
                this->Tom11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom11_Tapped);
            }
            break;
        case 103:
            {
                this->Tom9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom9_Tapped);
            }
            break;
        case 104:
            {
                this->Tom8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom8_Tapped);
            }
            break;
        case 105:
            {
                this->Tom7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom7_Tapped);
            }
            break;
        case 106:
            {
                this->Tom6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom6_Tapped);
            }
            break;
        case 107:
            {
                this->Tom4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom4_Tapped);
            }
            break;
        case 108:
            {
                this->Tom3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom3_Tapped);
            }
            break;
        case 109:
            {
                this->Tom2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom2_Tapped);
            }
            break;
        case 110:
            {
                this->Tom1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Tom1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Tom1_Tapped);
            }
            break;
        case 111:
            {
                this->CHat19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat19_Tapped);
            }
            break;
        case 112:
            {
                this->CHat18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat18_Tapped);
            }
            break;
        case 113:
            {
                this->CHat17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat17_Tapped);
            }
            break;
        case 114:
            {
                this->CHat16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat16_Tapped);
            }
            break;
        case 115:
            {
                this->CHat14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat14_Tapped);
            }
            break;
        case 116:
            {
                this->CHat13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat13_Tapped);
            }
            break;
        case 117:
            {
                this->CHat12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat12_Tapped);
            }
            break;
        case 118:
            {
                this->CHat11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat11_Tapped);
            }
            break;
        case 119:
            {
                this->CHat9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat9_Tapped);
            }
            break;
        case 120:
            {
                this->CHat8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat8_Tapped);
            }
            break;
        case 121:
            {
                this->CHat7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat7_Tapped);
            }
            break;
        case 122:
            {
                this->CHat6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat6_Tapped);
            }
            break;
        case 123:
            {
                this->CHat4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat4_Tapped);
            }
            break;
        case 124:
            {
                this->CHat3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat3_Tapped);
            }
            break;
        case 125:
            {
                this->CHat2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat2_Tapped);
            }
            break;
        case 126:
            {
                this->CHat1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->CHat1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::CHat1_Tapped);
            }
            break;
        case 127:
            {
                this->OHat19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat19_Tapped);
            }
            break;
        case 128:
            {
                this->OHat18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat18_Tapped);
            }
            break;
        case 129:
            {
                this->OHat17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat17_Tapped);
            }
            break;
        case 130:
            {
                this->OHat16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat16_Tapped);
            }
            break;
        case 131:
            {
                this->OHat14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat14_Tapped);
            }
            break;
        case 132:
            {
                this->OHat13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat13_Tapped);
            }
            break;
        case 133:
            {
                this->OHat12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat12_Tapped);
            }
            break;
        case 134:
            {
                this->OHat11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat11_Tapped);
            }
            break;
        case 135:
            {
                this->OHat9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat9_Tapped);
            }
            break;
        case 136:
            {
                this->OHat8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat8_Tapped);
            }
            break;
        case 137:
            {
                this->OHat7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat7_Tapped);
            }
            break;
        case 138:
            {
                this->OHat6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat6_Tapped);
            }
            break;
        case 139:
            {
                this->OHat4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat4_Tapped);
            }
            break;
        case 140:
            {
                this->OHat3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat3_Tapped);
            }
            break;
        case 141:
            {
                this->OHat2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat2_Tapped);
            }
            break;
        case 142:
            {
                this->OHat1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->OHat1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::OHat1_Tapped);
            }
            break;
        case 143:
            {
                this->Clap19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap19_Tapped);
            }
            break;
        case 144:
            {
                this->Clap18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap18_Tapped);
            }
            break;
        case 145:
            {
                this->Clap17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap17_Tapped);
            }
            break;
        case 146:
            {
                this->Clap16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap16_Tapped);
            }
            break;
        case 147:
            {
                this->Clap14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap14_Tapped);
            }
            break;
        case 148:
            {
                this->Clap13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap13_Tapped);
            }
            break;
        case 149:
            {
                this->Clap12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap12_Tapped);
            }
            break;
        case 150:
            {
                this->Clap11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap11_Tapped);
            }
            break;
        case 151:
            {
                this->Clap9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap9_Tapped);
            }
            break;
        case 152:
            {
                this->Clap8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap8_Tapped);
            }
            break;
        case 153:
            {
                this->Clap7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap7_Tapped);
            }
            break;
        case 154:
            {
                this->Clap6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap6_Tapped);
            }
            break;
        case 155:
            {
                this->Clap4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap4_Tapped);
            }
            break;
        case 156:
            {
                this->Clap3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap3_Tapped);
            }
            break;
        case 157:
            {
                this->Clap2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap2_Tapped);
            }
            break;
        case 158:
            {
                this->Clap1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Clap1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Clap1_Tapped);
            }
            break;
        case 159:
            {
                this->Snare19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare19_Tapped);
            }
            break;
        case 160:
            {
                this->Snare18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare18_Tapped);
            }
            break;
        case 161:
            {
                this->Snare17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare17_Tapped);
            }
            break;
        case 162:
            {
                this->Snare16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare16_Tapped);
            }
            break;
        case 163:
            {
                this->Snare14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare14_Tapped);
            }
            break;
        case 164:
            {
                this->Snare13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare13_Tapped);
            }
            break;
        case 165:
            {
                this->Snare12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare12_Tapped);
            }
            break;
        case 166:
            {
                this->Snare11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare11_Tapped);
            }
            break;
        case 167:
            {
                this->Snare9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare9_Tapped);
            }
            break;
        case 168:
            {
                this->Snare8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare8_Tapped);
            }
            break;
        case 169:
            {
                this->Snare7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare7_Tapped);
            }
            break;
        case 170:
            {
                this->Snare6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare6_Tapped);
            }
            break;
        case 171:
            {
                this->Snare4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare4_Tapped);
            }
            break;
        case 172:
            {
                this->Snare3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare3_Tapped);
            }
            break;
        case 173:
            {
                this->Snare2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare2_Tapped);
            }
            break;
        case 174:
            {
                this->Snare1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Snare1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Snare1_Tapped);
            }
            break;
        case 175:
            {
                this->Kick19 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick19))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick19_Tapped);
            }
            break;
        case 176:
            {
                this->Kick18 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick18))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick18_Tapped);
            }
            break;
        case 177:
            {
                this->Kick17 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick17))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick17_Tapped);
            }
            break;
        case 178:
            {
                this->Kick16 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick16))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick16_Tapped);
            }
            break;
        case 179:
            {
                this->Kick14 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick14))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick14_Tapped);
            }
            break;
        case 180:
            {
                this->Kick13 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick13))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick13_Tapped);
            }
            break;
        case 181:
            {
                this->Kick12 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick12))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick12_Tapped);
            }
            break;
        case 182:
            {
                this->Kick11 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick11))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick11_Tapped);
            }
            break;
        case 183:
            {
                this->Kick9 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick9))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick9_Tapped);
            }
            break;
        case 184:
            {
                this->Kick8 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick8))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick8_Tapped);
            }
            break;
        case 185:
            {
                this->Kick7 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick7))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick7_Tapped);
            }
            break;
        case 186:
            {
                this->Kick6 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick6_Tapped);
            }
            break;
        case 187:
            {
                this->Kick4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick4_Tapped);
            }
            break;
        case 188:
            {
                this->Kick3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick3_Tapped);
            }
            break;
        case 189:
            {
                this->Kick2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick2_Tapped);
            }
            break;
        case 190:
            {
                this->Kick1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->Kick1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::SimpG::TrackPage44::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&TrackPage44::Kick1_Tapped);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SimpG::TrackPage44::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


