#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Border;
                ref class Button;
                ref class ProgressBar;
                ref class MediaElement;
                ref class Image;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace SimpG
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class TrackPage34 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ trackGrid;
        private: ::Windows::UI::Xaml::Controls::Border^ KG1;
        private: ::Windows::UI::Xaml::Controls::Button^ playpause;
        private: ::Windows::UI::Xaml::Controls::Button^ clear;
        private: ::Windows::UI::Xaml::Controls::Button^ New;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ playhead;
        private: ::Windows::UI::Xaml::Controls::Button^ Pause;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ playheadBar;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ loc14;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1000111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1001111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1010111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1011111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1100111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1101111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1110111;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111000;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111001;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111010;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111011;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111100;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111101;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111110;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ _1111111;
        private: ::Windows::UI::Xaml::Controls::Image^ kickicon;
        private: ::Windows::UI::Xaml::Controls::Image^ snareicon;
        private: ::Windows::UI::Xaml::Controls::Image^ ohaticon;
        private: ::Windows::UI::Xaml::Controls::Image^ clapicon;
        private: ::Windows::UI::Xaml::Controls::Image^ chaticon;
        private: ::Windows::UI::Xaml::Controls::Image^ tomicon;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Tom1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ CHat1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ OHat1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Clap1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Snare1;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick14;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick13;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick12;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick11;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick9;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick7;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick6;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick4;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ Kick1;
    };
}

